spring.application.name=api-gateway

server.port=8079

# ==========================
# EUREKA
# ==========================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# ==========================
# AUTH SERVICE
# ==========================

spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**


# ==========================
# FOOD SERVICE
# ==========================

spring.cloud.gateway.server.webmvc.routes[1].id=food-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://FOOD-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/foods/**